export enum ACTION_TYPES {
  FETCH_MENU = 'FETCH_MENU',
  FETCH_CATEGORY_POSTS = 'FETCH_CATEGORY_POSTS',
  FETCH_SINGULAR = 'FETCH_SINGULAR',
  IS_FETCHING = 'IS_FETCHING',
  IS_DISPLAYING = 'IS_DISPLAYING',
  IS_MENU_OPEN = 'IS_MENU_OPEN',
  SET_REF = 'SET_REF',
}

export enum ACTION_STATES {
  SUCCESS = 'SUCCESS',
  FAIL = 'FAIL',
}
